# Group B CellOT: condition = cell_type_status (cd8/non_cd8).
# CellOT learns: non_cd8 -> cd8 transition.
# Holdout: entire human species (OOD test = can this transition generalize to human?)
data:
  type: cell
  source: non_cd8
  target: cd8
  condition: condition
  path: datasets/speciesot-human-mouse/cd8_nothymo_holdout_swapped_v07.h5ad

dataloader:
  batch_size: 128
  shuffle: true

datasplit:
  name: train_test
  holdout:
    species: human
  groupby: condition
  test_size: 0.2
  random_state: 0
