"""Synthetic mouse->human toy with a KNOWN ground-truth transport.

The toy is engineered so the correct answer is unambiguous, which lets us prove the
mechanism that motivates unbalanced OT *before* touching real data (mirrors the
ae_study "correctness guards" idea).

Construction
------------
- ``K`` shared cell types, present in BOTH species, as Gaussian blobs.
- A single global affine deformation ``Phi(x) = x @ A.T + b`` is the TRUE mouse->human
  map on shared structure. Human shared cells are generated by sampling shared-type
  points and pushing them through ``Phi`` (so ``T* = Phi`` is the exact transport on
  the shared part, per cell, regardless of composition).
- **Composition skew**: mouse and human use DIFFERENT type proportions. A balanced map
  is forced to move mass across type boundaries to match the human marginal; the true
  per-cell map ``Phi`` does not. This is corruption source #1.
- **Mouse-only blob**: an extra cluster present only in mouse, with no human counterpart.
  A balanced map must transport it somewhere in the human cloud (corruption source #2);
  the correct fate is to DISCARD it (only unbalanced OT can).

Returned ``ToyData`` carries everything the guards need: the clouds, per-cell type
labels (blob = -1), a boolean shared mask, and the ground-truth ``Phi``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import numpy as np


@dataclass
class ToyData:
    X: np.ndarray            # mouse (source) cells: shared + blob, shape (n_src, d)
    Y: np.ndarray            # human (target) cells: shared only, shape (n_tgt, d)
    src_labels: np.ndarray   # per source cell: type id in [0..K), or -1 for the blob
    tgt_labels: np.ndarray   # per target cell: type id in [0..K)
    shared_mask: np.ndarray  # bool over source cells: True where a human counterpart exists
    Phi: Callable[[np.ndarray], np.ndarray]  # the TRUE map on shared structure
    A: np.ndarray
    b: np.ndarray


def _affine(A: np.ndarray, b: np.ndarray) -> Callable[[np.ndarray], np.ndarray]:
    def phi(x: np.ndarray) -> np.ndarray:
        return np.asarray(x) @ A.T + b
    return phi


def _rotation(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s], [s, c]])


def make_toy(
    n_total: int = 1200,
    dim: int = 2,
    K: int = 4,
    ring_radius: float = 4.0,
    blob_frac: float = 0.25,
    noise: float = 0.35,
    theta: float = 0.6,
    scale: tuple[float, float] = (1.25, 0.8),
    shift: tuple[float, float] = (3.0, -2.0),
    blob_center: tuple[float, float] = (0.0, 6.5),
    seed: int = 0,
) -> ToyData:
    """Build the toy. ``dim`` must be 2 for the ring layout used here."""
    assert dim == 2, "toy layout is 2-D for clear visualization"
    rng = np.random.default_rng(seed)

    # Shared-type centers on a ring (canonical mouse frame).
    angles = np.linspace(0, 2 * np.pi, K, endpoint=False)
    centers = ring_radius * np.c_[np.cos(angles), np.sin(angles)]

    # Deliberately mismatched compositions over the K shared types.
    p_mouse = np.array([0.55, 0.25, 0.12, 0.08])[:K]
    p_human = np.array([0.10, 0.20, 0.30, 0.40])[:K]
    p_mouse = p_mouse / p_mouse.sum()
    p_human = p_human / p_human.sum()

    n_blob = int(round(blob_frac * n_total))
    n_shared_src = n_total - n_blob
    n_tgt = n_total

    # True deformation on shared structure.
    A = _rotation(theta) @ np.diag(np.array(scale))
    b = np.array(shift)
    Phi = _affine(A, b)

    # Mouse shared cells (mouse composition), in canonical frame.
    src_counts = rng.multinomial(n_shared_src, p_mouse)
    Xs, src_lab = [], []
    for k, ck in enumerate(src_counts):
        Xs.append(centers[k] + noise * rng.standard_normal((ck, dim)))
        src_lab.append(np.full(ck, k))
    Xs = np.vstack(Xs)
    src_lab = np.concatenate(src_lab)

    # Mouse-only blob (no human counterpart).
    Xb = np.array(blob_center) + noise * rng.standard_normal((n_blob, dim))
    X = np.vstack([Xs, Xb])
    src_labels = np.concatenate([src_lab, np.full(n_blob, -1)])
    shared_mask = src_labels >= 0

    # Human cells: sample shared-type points (human composition) in the canonical
    # frame, then push through Phi so that T* = Phi is exact on shared structure.
    tgt_counts = rng.multinomial(n_tgt, p_human)
    Yc, tgt_lab = [], []
    for k, ck in enumerate(tgt_counts):
        Yc.append(centers[k] + noise * rng.standard_normal((ck, dim)))
        tgt_lab.append(np.full(ck, k))
    Yc = np.vstack(Yc)
    tgt_labels = np.concatenate(tgt_lab)
    Y = Phi(Yc)

    # Shuffle so downstream code cannot rely on ordering.
    perm_s = rng.permutation(len(X))
    perm_t = rng.permutation(len(Y))
    return ToyData(
        X=X[perm_s], Y=Y[perm_t],
        src_labels=src_labels[perm_s], tgt_labels=tgt_labels[perm_t],
        shared_mask=shared_mask[perm_s], Phi=Phi, A=A, b=b,
    )
